apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deploy-for-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: deploy-pod
      labels:
        env: test
    spec:
      containers:
        - name: nginx-container
          image: nginx:2
          ports:
            - containerPort: 80