# Use the official NGINX base image
FROM nginx:latest

# Set the working directory in the container
WORKDIR /usr/share/nginx/html

# Copy your custom index.html file to the container
COPY index.html .

# Expose port 80 (the default port for NGINX)
EXPOSE 80
